#' Performing optimization and penalized K-means clustering
#' 
#'
#' This function is a user-friendly wrapper integrating the dOpt and dClust functions. It only requires a dataset and an id vector. It starts by doing all necessary optimizations, both on the smallest sample size that is needed to perform the most stable clustering, and to identify the optimal penalty. It then performs clustering based on the values identified in the optimization step. 
#' @importFrom dplyr sample_n
#' @param inDataFrameScaled A dataframe with the data that will be used to create the clustering. The data in this dataframe should be scaled in a proper way. Empirically, many datasets seem to be clustered in a meaningful way if they are scaled with the dScale function.
#' @param penalties This argument decides whether a single penalty will be used for clustering, or if multiple penalties will be evaluated to identify the optimal one. The suggested default values are empirically defined and might not be optimal for a specific dataset, but the algorithm will warn if the most optimal values are on the borders of the range. Note that when this offset is 0, there is no penalization, which means that the algorithm runs normal K-means clustering.
#' @param sampleSizes This controls what fraction of the dataset that will be used to run the penalty optimization. A single value or a vector of values are accepted. "default" results in the full file in files up to 10000 events. From larger files, a sample of 10000 random rows is used. A user specified number is accepted.
#' @param fMeasureSampleSize The size of the dataset used to find the optimal solution out of the many generated by the penalty optimization at each sample size. "default" results in the full file in files up to 10000 events. From larger files, a sample of 10000 random rows is used. A user specified number is accepted.
#' @param dualClustSetup A dataframe with two columns: the first specifying which step (1 or 2) the variable should be included in, the second specifying ht ecolumn name for the variable in question. Iit is used if a two-step clustering should be performed, eg in the case where phenotypic clustering should be performed, followed by clustering on functional variables.
#' @param k Number of initial cluster centers. The higher the number, the greater the precision of the clustering, but the computing time is also increased with the number of starting points. Default is 30. If penalties=0, k-means clustering with k clusters will be performed.
#' @param minCRIImprovement This is the stop criterion for the penalty optimization algorithm: the more iterations that are run, the smaller will the improvement of the corrected Rand index be, and this sets the threshold when the inner iterations stop. Defaults to 0.01, or 1 percent. 
#' @param maxIter The maximal number of iterations that are performed in the penalty optimization. 
#' @param maxCRI This is the stop criterion for the iterative optimization of the sample size: the maximum corrected Rand index that is acceptable. Defaults to 0.05, or 5 percent difference between sets of two full dataset allocations based on clusterings of a certain sample size.
#' @param withOrigoClust Defines whether a cluster in origo should be allowed. In most instances, this makes no biological sense, and hence, default is "no".
#' @param ids Optionally, a vector of the same length as rows in the inDataFrameScaled can be included. If so, it is used to generate a final analysis, where a table of the fraction of observations for each individual and each cluster is created.
#' @seealso \code{\link{dAllocate}}
#' @return A nested list with varying components depending on the setup above:
#' \describe{
#'    \item{clusterVector}{A vector with the same length as number of rows in the inDataFrameUsed, where the cluster identity of each observation is noted.}
#'    \item{clusterCenters}{A matrix containing information about where the centers are in all the variables that contributed to creating the cluster with the given penalty term. Is used by dAllocate.}
#'    \item{penaltyOptList}{This is only included when multiple penalties are run. A list of two dataframes:
#'    \describe{
#'              \item{penaltyOpt.df}{A one row dataframe with all the optimal settings from the penalty optimization. The "withOrigoClust" information tells the user if the solution with or without a cluster in origo gives the most optimal solution.}
#'              \item{meanOptimDf}{A dataframe with the information about the results with all tested penalty values.}
#'            }
#'     }
#'     \item{sampleSizeOptList}{This is only included if multiple sample sizes are run. It is a dataframe, in which each row represents one sample size, and in which the last row is thus the chosen, optimal sample size. It has the following columns:
#'     \describe{
#'               \item{SampleSize}{This column shows the sample size of each boot strap subsampling in the optimization procedure.}
#'               \item{Lowest distance}{This vector shows the optimal stability, expressed as the lowest distance between the bootstrap subsampling runs at each of the boot strap subsamling sizes.}
#'               \item{Improvement}{Here, the improvement, expressed as a fraction between 0 and 1 is shown. When the improvement is less than minCRIImprovement, the algorithm automatically stops.}
#'              } 
#'     }
#'     \item{idClusterFractions}{If a valid ids vector is included, this dataframe is returned that contains the what fraction of each id that is present in each cluster. Calculated on a per id basis.}

#' }
#' @examples
#' #Generate a default size dataframe with bimodally distributed data
#' x <- generateBimodalData(samplings=2)
#'
#' #Scale this datamframe
#' x_scaled <- dScale(x[,2:ncol(x)])
#'
#' #Set a reasonable working directory, e.g.
#' setwd("~/Desktop")
#'
#' #First, just run with the standard settings
#' xClustObject <- dClust(x_scaled, ids=x[,1])
#'
#' #Look at the result
#' str(xClustObject)
#' 
#' #Then try changing to a few different sample sizes
#' xClustObject <- dClust(x_scaled, ids=x[,1], sampleSizes=c(100, 500, 1000))
#'
#' #Look at the result
#' str(xClustObject)
#' 
#' @export dClust
dClust <- function(inDataFrameScaled, penalties=c(0,2,4,8,16,32,64,128), sampleSizes="default", fMeasureSampleSize="default", k=30, minCRIImprovement=0.01, maxCRI=0.05, maxIter=100, withOrigoClust="no", ids){

  if(missing(dualClustSetup)==TRUE){
    firstClusterNumber <- ifelse(withOrigoClust=="no", 1, 0)
    dClustResult <- dClustCoFunction(inDataFrameScaled, firstClusterNumber=firstClusterNumber, penalties=penalties, sampleSizes=sampleSizes, fMeasureSampleSize=fMeasureSampleSize, k=k, minCRIImprovement=minCRIImprovement, maxCRI=maxCRI, maxIter=maxIter, withOrigoClust=withOrigoClust, ids=ids)
  }
  
  #Here, the dual cluster setup is created
  if(missing(dualClustSetup)==FALSE){
    inDataColumns <- dualClustSetup[,2]
    inDataFrameFirst <- inDataFrameScaled[,inDataColumns[which(dualClustSetup[,1])==1]]
    dClustResultFirst <- dClustCoFunction(inDataFrameFirst, penalties=penalties, sampleSizes=sampleSizes, fMeasureSampleSize=fMeasureSampleSize, k=k, minCRIImprovement=minCRIImprovement, maxCRI=maxCRI, maxIter=maxIter, withOrigoClust=withOrigoClust, ids=ids)
    
    #After this first step, clustering is performed within each of the clusters produced by the dClustResultFirst
    inDataFrameSecondList <- list()
    for(i in 1:length(unique(dClustResultFirst$clusterVector))){
      inDataFrameSecondList[[i]] <- inDataFrameSecond[which(dClustResultFirst$clusterVector==i),]
    }
    
    #Now create the list of cluster numbers
    firstClusterNumberList <- list()
    for(i in 1:length(unique(dClustResultFirst$clusterVector))){
      rightNumberSize <- 100*i
      firstClusterNumberList[[i]] <- rightNumberSize+ifelse(withOrigoClust=="no", 1, 0)
    }
    
    dClustResultTrainFuncList <- mapply(dClust, clusterDatasetList, firstClusterNumberList, MoreArgs=list(penalties=penalties, sampleSizes=sampleSizes, fMeasureSampleSize=fMeasureSampleSize, k=k, minCRIImprovement=minCRIImprovement, maxCRI=maxCRI, maxIter=maxIter, withOrigoClust=withOrigoClust, ids=ids), SIMPLIFY=FALSE)
    
  }
  
  return(dClustResult)
}
  